import tag from './tag.js';
import countActionInHour from '../services/countActionInHour.js';
import countActionInDay from '../services/countActionInDay.js';
import currentHour from '../services/currentHour.js';
import countActionInTotal from '../services/countActionInTotal.js';
const homePageChart = async ()=>{
    const hour = currentHour();
    const likeHour = await countActionInHour({action:'like',hour:hour});
    const commentHour = await countActionInHour({action:'comment',hour:hour});
    const followHour = await countActionInHour({action:'follow',hour:hour});
    const likeDay = await countActionInDay({action:'like',hour:hour});
    const commentDay = await countActionInDay({action:'comment',hour:hour});
    const followDay = await countActionInDay({action:'follow',hour:hour});
    const likeTotal = await countActionInTotal('like');
    const commentTotal = await countActionInTotal('comment');
    const followTotal = await countActionInTotal('follow');
    const table = tag({name:'table',classes:['homepage_content_data']});
    const tr1 = tag({name:'tr'});
    const td1 = tag({name:'td',html:''});
    const td2 = tag({name:'td',html:'Like'});
    const td3 = tag({name:'td',html:'Comment'});
    const td4 = tag({name:'td',html:'Follow'});
    tr1.append(td1,td2,td3,td4);
    const tr2 = tag({name:'tr'});
    const td5 = tag({name:'td',html:'Current Hour'});
    const td6 = tag({name:'td',html:`${likeHour}`});
    const td7 = tag({name:'td',html:`${commentHour}`});
    const td8 = tag({name:'td',html:`${followHour}`});
    tr2.append(td5,td6,td7,td8);
    const tr3 = tag({name:'tr'});
    const td9 = tag({name:'td',html:'Last 24 Hour'});
    const td10 = tag({name:'td',html:`${likeDay}`});
    const td11 = tag({name:'td',html:`${commentDay}`});
    const td12 = tag({name:'td',html:`${followDay}`});
    tr3.append(td9,td10,td11,td12);
    const tr4 = tag({name:'tr'});
    const td13 = tag({name:'td',html:'Total'});
    const td14 = tag({name:'td',html:`${likeTotal}`});
    const td15= tag({name:'td',html:`${commentTotal}`});
    const td16 = tag({name:'td',html:`${followTotal}`});
    tr4.append(td13,td14,td15,td16);
    table.append(tr1,tr2,tr3,tr4);
    return table;
};
export default homePageChart;